const courseTools = require('./course.tools');
const assignmentTools = require('./assignment.tools');
const taskTools = require('./task.tools');
const materialTools = require('./material.tools');

const registry = {
  [courseTools.declaration.name]: courseTools,
  [assignmentTools.declaration.name]: assignmentTools,
  [taskTools.declaration.name]: taskTools,
  [materialTools.declaration.name]: materialTools,
};

const toolDeclarations = Object.values(registry).map(tool => tool.declaration);

/**
 * Safely executes a registered tool.
 * @param {string} toolName - Name of the tool to execute.
 * @param {object} args - Arguments generated by the LLM.
 * @param {object} context - Trusted user context (e.g., { id, name, role }).
 * @returns {object} - Safe execution result.
 */
async function executeTool(toolName, args, context) {
  const tool = registry[toolName];
  if (!tool) {
    console.warn(`[Security] Attempted to execute unknown tool: ${toolName}`);
    return { error: `Tool '${toolName}' is not recognized or not authorized.` };
  }

  try {
    // 1. Strip out any malicious injected 'userId' from the model args
    // We enforce authorization strictly via the trusted `context` object provided by the server.
    if (args && args.userId) {
      delete args.userId;
    }

    // 2. Validate arguments using the specific tool's Zod schema
    const validArgs = tool.schema ? tool.schema.parse(args || {}) : (args || {});

    // 3. Execute the tool's handler
    const result = await tool.handler(validArgs, context);
    return result;

  } catch (error) {
    if (error.name === 'ZodError') {
      // Return validation errors back to the LLM so it can correct itself if necessary
      return { error: 'Validation failed for arguments', details: error.errors };
    }
    
    // Log internal errors but do not expose raw stack traces to the LLM/User
    console.error(`[Tool Execution Error] ${toolName}:`, error);
    return { error: 'Internal database or execution error occurred while running the tool.' };
  }
}

module.exports = {
  toolDeclarations,
  executeTool,
};
